### ISSUE TITLE
Item link doesn't work correctly

### ISSUE THREAD

**Issue by avanriet** [icampana/MasonryGrid#1]
When you enter the url with the Browse option the complete url will be used here (http://www.domain.com/page) instead of only /page. When you click an item the link won't be set correct: http://www.domain.com/http://domain.com/page

Screenshot:
![ip_masonry_plugin_bug](https://cloud.githubusercontent.com/assets/7957254/6506517/015edc50-c34c-11e4-96ef-0c4a41a202d6.png)

**Comment by icampana** [comment]
Thanks for reporting! Give me a couple hours and I'll fix it, I always
thought that links would be used just for internal links (to other pages
inside the website), but you're right, could be used for external links.

On Thu, Mar 5, 2015 at 9:29 AM, Avriet notifications@github.com wrote:

> When you enter the url with the Browse option the complete url will be
> used here (http://www.domain.com/page) instead of only /page. When you
> click an item the link won't be set correct:
> http://www.domain.com/http://domain.com/page
> 
> Screenshot:
> [image: ip_masonry_plugin_bug]
> https://cloud.githubusercontent.com/assets/7957254/6506517/015edc50-c34c-11e4-96ef-0c4a41a202d6.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icampana/MasonryGrid/issues/1.

## 

Atte.
Iván Gabriel Campaña Naranjo
http://icampana.blogspot.com/
Mov.  593-9-830 1093
Casa 593-4-601 6265

**Comment by icampana** [comment]
Correction made, should fix the issue, let me know if everything is working all right!

**Comment by avanriet** [comment]
Awesome job, works perfectly now!
